minimum_pre_commit_version: "3.2.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: ^(?:LICENSE|LICENSES/)
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=no]
      - id: trailing-whitespace
        exclude: ^(?:LICENSE|LICENSES/)
